defaults:
  - _self_
  - data: null
  - optim: null
  - inr: null
  - wandb: null

data:
  dataset_name: "pendulum"
  dir: "xxx"
  seed: 123

optim:
  epochs: 1000
  batch_size_train: 16
  batch_size_val: 32
  lr: 0.001
  init_type: 'default'
  init_gain: 0.15
  regul:

model:
  hidden_c: 64
  state_c: 2
  code_c: 2
  method: 'rk4'
  factor: 1
  is_complete: False
  type_augment: "serie"
  options:
  teacher_forcing_init: 0.99
  teacher_forcing_decay: 0.99
  teacher_forcing_update: 10

wandb:
  entity: "xxx"
  project: "xxx"
  name: 
  id: 
  dir:
  sweep_id:
  saved_checkpoint : False
  checkpoint_path :
