defaults:
  - _self_
  - data: null
  - optim: null
  - inr: null
  - wandb: null

data:
  dataset_name: "pendulum"
  dir: /home/kassai/code/ERM/exp_gen/adapt
  seed: 123
  env_name: 
  ntrain: 
  ntest:
  num_env:

optim:
  epochs: 1000
  batch_size_train: 16
  batch_size_val: 32

pretrain:
  run_name:

model:
  state_c: 2

wandb:
  entity: "spatiotemp-isir"
  project: "fuels"
  name: 
  id: 
  dir:
  sweep_id:
  saved_checkpoint : False
  checkpoint_path :