defaults:
  - _self_
  - data: null
  - optim: null
  - inr: null
  - wandb: null

data:
  dataset_name: "pendulum"
  dir: "/home/kassai/code/FUELS/exp_gen/adapt"
  seed: 123

optim:
  epochs: 1000
  batch_size_train: 16
  batch_size_val: 32
  init_type: 'default'
  init_gain: 0.15
  lr:

model:
  hidden_c: 64
  state_c: 2
  method: 'rk4'
  options:
  teacher_forcing_init: 0.99
  teacher_forcing_decay: 0.99
  teacher_forcing_update: 10

pretrain:
  run_name:
  
wandb:
  entity: "spatiotemp-isir"
  project: "fuels"
  name: 
  id: 
  dir:
  sweep_id:
  saved_checkpoint : False
  checkpoint_path :